"use strict";
let x = 3, y = 6;
let Add, Sub, Mul, Div;
Add = x + y;
console.log("Addition of x and y = " + Add);
Sub = x - y;
console.log("\nSubtraction of x and y = " + Sub);
Mul = x * y;
console.log("\nMultiplication of x and y = " + Mul);
Div = x / y;
console.log("\nDivision of x and y = " + Div);
